/**
 * feature-registry.ts
 *
 * The canonical list of every billable feature key in the platform.
 * Adding a new billable feature requires ONLY:
 *   1. Adding an entry here (documentation / validation)
 *   2. Inserting a FeatureDefinition record in the DB (seed script)
 *   3. Adding the feature to the relevant BillingPlan records
 *
 * No changes to entitlement-engine, usage-engine, or quota.ts are needed.
 */

export type FeatureType = "boolean" | "quota" | "count" | "storage" | "metered";
export type ResetPeriod = "monthly" | "yearly" | "never";

export interface FeatureMeta {
  key: string;
  name: string;
  description: string;
  type: FeatureType;
  unit: string;
  resetPeriod: ResetPeriod;
}

/** Master list of all supported feature keys */
export const FEATURE_KEYS = {
  // ── AI usage ──────────────────────────────────────────────────────────────
  AI_MESSAGES: "ai_messages",
  AI_TOKENS_PROMPT: "ai_tokens_prompt",
  AI_TOKENS_COMPLETION: "ai_tokens_completion",
  AI_TOKENS_EMBEDDING: "ai_tokens_embedding",

  // ── Storage ───────────────────────────────────────────────────────────────
  KNOWLEDGE_STORAGE_MB: "knowledge_storage_mb",
  ATTACHMENT_STORAGE_MB: "attachment_storage_mb",

  // ── Resource counts ───────────────────────────────────────────────────────
  MAX_TEAM_MEMBERS: "max_team_members",
  MAX_AGENTS: "max_agents",
  MAX_BOTS: "max_bots",
  MAX_CHANNELS: "max_channels",
  MAX_TELEGRAM_CHANNELS: "max_telegram_channels",
  MAX_WHATSAPP_NUMBERS: "max_whatsapp_numbers",
  MAX_FACEBOOK_PAGES: "max_facebook_pages",
  MAX_INSTAGRAM_ACCOUNTS: "max_instagram_accounts",
  MAX_MESSENGER_PAGES: "max_messenger_pages",
  MAX_CONTACTS: "max_contacts",
  MAX_COMPANIES: "max_companies",
  MAX_PIPELINES: "max_pipelines",
  MAX_WORKFLOWS: "max_workflows",
  MAX_AUTOMATIONS: "max_automations",
  MAX_KNOWLEDGE_FILES: "max_knowledge_files",

  // ── Quota features ────────────────────────────────────────────────────────
  API_REQUESTS: "api_requests",
  WORKFLOW_RUNS: "workflow_runs",
  AUTOMATION_RUNS: "automation_runs",
  SCHEDULED_JOBS: "scheduled_jobs",
  EXPORTS: "exports",
  VOICE_MINUTES: "voice_minutes",
  OCR_PAGES: "ocr_pages",
  EMAIL_CREDITS: "email_credits",
  SMS_CREDITS: "sms_credits",
  IMAGE_GENERATIONS: "image_generations",
  VIDEO_GENERATIONS: "video_generations",

  // ── Boolean features ──────────────────────────────────────────────────────
  ADVANCED_AI: "advanced_ai",
  KNOWLEDGE_ENABLED: "knowledge_enabled",
  QDRANT_SEARCH: "qdrant_search",
  API_ACCESS: "api_access",
  WHITE_LABEL: "white_label",
  CUSTOM_DOMAIN: "custom_domain",
  AUDIT_LOGS: "audit_logs",
  WEBHOOKS: "webhooks",
  SSO: "sso",
  PRIORITY_SUPPORT: "priority_support"
} as const;

export type FeatureKey = typeof FEATURE_KEYS[keyof typeof FEATURE_KEYS];

/**
 * Built-in feature metadata used by the seed script and for display.
 * This is NOT used for entitlement resolution — plan features are the source of truth.
 */
export const FEATURE_REGISTRY: Record<string, FeatureMeta> = {
  [FEATURE_KEYS.AI_MESSAGES]: {
    key: FEATURE_KEYS.AI_MESSAGES,
    name: "AI Messages",
    description: "Number of AI-generated replies per billing period",
    type: "quota",
    unit: "message",
    resetPeriod: "monthly"
  },
  [FEATURE_KEYS.AI_TOKENS_PROMPT]: {
    key: FEATURE_KEYS.AI_TOKENS_PROMPT,
    name: "Prompt Tokens",
    description: "Input tokens consumed by AI models",
    type: "quota",
    unit: "token",
    resetPeriod: "monthly"
  },
  [FEATURE_KEYS.AI_TOKENS_COMPLETION]: {
    key: FEATURE_KEYS.AI_TOKENS_COMPLETION,
    name: "Completion Tokens",
    description: "Output tokens generated by AI models",
    type: "quota",
    unit: "token",
    resetPeriod: "monthly"
  },
  [FEATURE_KEYS.KNOWLEDGE_STORAGE_MB]: {
    key: FEATURE_KEYS.KNOWLEDGE_STORAGE_MB,
    name: "Knowledge Storage",
    description: "Total knowledge base storage capacity",
    type: "storage",
    unit: "MB",
    resetPeriod: "never"
  },
  [FEATURE_KEYS.ATTACHMENT_STORAGE_MB]: {
    key: FEATURE_KEYS.ATTACHMENT_STORAGE_MB,
    name: "Attachment Storage",
    description: "Total file attachment storage capacity",
    type: "storage",
    unit: "MB",
    resetPeriod: "never"
  },
  [FEATURE_KEYS.MAX_TEAM_MEMBERS]: {
    key: FEATURE_KEYS.MAX_TEAM_MEMBERS,
    name: "Team Members",
    description: "Maximum number of team members / seats",
    type: "count",
    unit: "seat",
    resetPeriod: "never"
  },
  [FEATURE_KEYS.MAX_AGENTS]: {
    key: FEATURE_KEYS.MAX_AGENTS,
    name: "AI Agents",
    description: "Maximum number of AI agents",
    type: "count",
    unit: "agent",
    resetPeriod: "never"
  },
  [FEATURE_KEYS.MAX_BOTS]: {
    key: FEATURE_KEYS.MAX_BOTS,
    name: "Bots",
    description: "Maximum number of chatbots",
    type: "count",
    unit: "bot",
    resetPeriod: "never"
  },
  [FEATURE_KEYS.MAX_CHANNELS]: {
    key: FEATURE_KEYS.MAX_CHANNELS,
    name: "Channels",
    description: "Maximum number of connected channels",
    type: "count",
    unit: "channel",
    resetPeriod: "never"
  },
  [FEATURE_KEYS.MAX_TELEGRAM_CHANNELS]: {
    key: FEATURE_KEYS.MAX_TELEGRAM_CHANNELS,
    name: "Telegram Channels",
    description: "Maximum number of Telegram channels",
    type: "count",
    unit: "channel",
    resetPeriod: "never"
  },
  [FEATURE_KEYS.MAX_WHATSAPP_NUMBERS]: {
    key: FEATURE_KEYS.MAX_WHATSAPP_NUMBERS,
    name: "WhatsApp Numbers",
    description: "Maximum number of WhatsApp Business numbers",
    type: "count",
    unit: "number",
    resetPeriod: "never"
  },
  [FEATURE_KEYS.MAX_FACEBOOK_PAGES]: {
    key: FEATURE_KEYS.MAX_FACEBOOK_PAGES,
    name: "Facebook Pages",
    description: "Maximum number of Facebook Pages",
    type: "count",
    unit: "page",
    resetPeriod: "never"
  },
  [FEATURE_KEYS.MAX_INSTAGRAM_ACCOUNTS]: {
    key: FEATURE_KEYS.MAX_INSTAGRAM_ACCOUNTS,
    name: "Instagram Accounts",
    description: "Maximum number of Instagram accounts",
    type: "count",
    unit: "account",
    resetPeriod: "never"
  },
  [FEATURE_KEYS.API_REQUESTS]: {
    key: FEATURE_KEYS.API_REQUESTS,
    name: "API Requests",
    description: "Monthly API call quota",
    type: "quota",
    unit: "request",
    resetPeriod: "monthly"
  },
  [FEATURE_KEYS.WORKFLOW_RUNS]: {
    key: FEATURE_KEYS.WORKFLOW_RUNS,
    name: "Workflow Runs",
    description: "Monthly workflow execution quota",
    type: "quota",
    unit: "run",
    resetPeriod: "monthly"
  },
  [FEATURE_KEYS.VOICE_MINUTES]: {
    key: FEATURE_KEYS.VOICE_MINUTES,
    name: "Voice Minutes",
    description: "Monthly voice call minutes",
    type: "quota",
    unit: "minute",
    resetPeriod: "monthly"
  },
  [FEATURE_KEYS.ADVANCED_AI]: {
    key: FEATURE_KEYS.ADVANCED_AI,
    name: "Advanced AI",
    description: "Access to GPT-4, Claude, and premium AI models",
    type: "boolean",
    unit: "",
    resetPeriod: "never"
  },
  [FEATURE_KEYS.KNOWLEDGE_ENABLED]: {
    key: FEATURE_KEYS.KNOWLEDGE_ENABLED,
    name: "Knowledge Base",
    description: "Enable knowledge base and RAG search",
    type: "boolean",
    unit: "",
    resetPeriod: "never"
  },
  [FEATURE_KEYS.QDRANT_SEARCH]: {
    key: FEATURE_KEYS.QDRANT_SEARCH,
    name: "Vector Search",
    description: "Enable Qdrant vector search for knowledge",
    type: "boolean",
    unit: "",
    resetPeriod: "never"
  },
  [FEATURE_KEYS.API_ACCESS]: {
    key: FEATURE_KEYS.API_ACCESS,
    name: "API Access",
    description: "Enable programmatic API access",
    type: "boolean",
    unit: "",
    resetPeriod: "never"
  },
  [FEATURE_KEYS.WHITE_LABEL]: {
    key: FEATURE_KEYS.WHITE_LABEL,
    name: "White Label",
    description: "Remove ChatZi branding",
    type: "boolean",
    unit: "",
    resetPeriod: "never"
  },
  [FEATURE_KEYS.CUSTOM_DOMAIN]: {
    key: FEATURE_KEYS.CUSTOM_DOMAIN,
    name: "Custom Domain",
    description: "Use a custom domain for the chat widget",
    type: "boolean",
    unit: "",
    resetPeriod: "never"
  },
  [FEATURE_KEYS.AUDIT_LOGS]: {
    key: FEATURE_KEYS.AUDIT_LOGS,
    name: "Audit Logs",
    description: "Access to detailed audit logs",
    type: "boolean",
    unit: "",
    resetPeriod: "never"
  }
};
